version: '3.8'

services:
  ubuntu-desktop:
    build: .
    container_name: ubuntu-novnc
    ports:
      - "6080:6080"  # noVNC web interface
      - "5901:5901"  # VNC port (optional)
    environment:
      - DISPLAY=:1
    restart: unless-stopped
    volumes:
      - ./shared:/home/vncuser/shared  # Optional: shared folder
    shm_size: 2g  # Increase shared memory for better performance